name: fitbudi_1
description: A new Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  logger: ^2.5.0
  flutter_svg: ^1.0.0
  provider: ^6.1.0
  shared_preferences: ^2.0.8
  intl: ^0.19.0
  table_calendar: ^3.0.0
  url_launcher: ^6.2.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^5.0.0
  record: ^5.0.4
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  flutter_stripe: ^11.3.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/assets/image.png
   - lib/assets/images.jpg